name: Build, Test & Prove

# Quand lancer ce pipeline : a chaque push et chaque pull request sur main.
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Recupere ton code sur le serveur.
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Installe Alire (le gestionnaire de paquets Ada).
      - name: Install Alire
        uses: alire-project/setup-alire@v4

      # 3. Compile le projet principal.
      - name: Build
        run: alr build

      # 4. Compile et lance les tests AUnit.
      # Recupere explicitement AUnit (dependance du projet de test).
      - name: Get AUnit
        run: alr with aunit

      # Compile et lance les tests AUnit.
      - name: Tests
        run: |
          alr exec -- gprbuild -P radar_fw_tests.gpr
          alr exec -- ./bin/run_tests

      # 5. Rejoue la preuve SPARK.
      - name: SPARK proof
        run: alr gnatprove