name: Build, Test & Prove

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Alire
        uses: alire-project/setup-alire@v4

      # Resout et telecharge TOUTES les dependances declarees (AUnit inclus).
      - name: Resolve dependencies
        run: alr update

      - name: Build
        run: alr build

      - name: Build tests
        run: alr exec -- gprbuild -p -P radar_fw_tests.gpr

      - name: Run tests
        run: ./bin/run_tests

      - name: SPARK proof
        run: alr gnatprove